<?php

namespace NP\Bundle\ResourcesBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends SortableRepository {

    public function deleteOne($id)
    {
        $this->deleteGroup(array($id));
    }

    public function deleteGroup($ids)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->delete('NPResourcesBundle:Category', 'c')
                ->where($qb->expr()->in('c.id', $ids))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }

    public function publishGroup($id) {
        $qb = $this->createQueryBuilder('n');

        $qb->update('NPResourcesBundle:Category', 'c')
                ->set('c.published', 1)
                ->where($qb->expr()->in('c.id', $id))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }

    public function unpublishGroup($id) {
        $qb = $this->createQueryBuilder('c');
        $qb->update('NPResourcesBundle:Category', 'c')
                ->set('c.published', 0)
                ->where($qb->expr()->in('c.id', $id))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }
}
