np_core_user_index:
    pattern: /
    defaults: { _controller: NPCoreBundle:User:index }

np_core_user_show:
    pattern: /{id}/show
    defaults: { _controller: NPCoreBundle:User:show }
    requirements:
      id: \d+

np_core_user_new:
    pattern: /new
    defaults: { _controller: NPCoreBundle:User:new }

np_core_user_edit:
    pattern: /{id}/edit
    defaults: { _controller: NPCoreBundle:User:edit }
    requirements:
      id: \d+

np_core_user_delete:
    pattern: /{id}/delete
    defaults: { _controller: NPCoreBundle:User:delete }
    requirements:
      id: \d+

np_core_user_groupprocess:
    pattern: /groupprocess
    defaults: { _controller: NPCoreBundle:User:groupProcess }
