np_resources_category_index:
    pattern: /
    defaults: { _controller: NPResourcesBundle:Category:index }

np_resources_category_show:
    pattern: /{id}/show
    defaults: { _controller: NPResourcesBundle:Category:show }
    requirements:
      id: \d+

np_resources_category_new:
    pattern: /new
    defaults: { _controller: NPResourcesBundle:Category:new }

np_resources_category_edit:
    pattern: /{id}/edit
    defaults: { _controller: NPResourcesBundle:Category:edit }
    requirements:
      id: \d+

np_resources_category_delete:
    pattern: /{id}/delete
    defaults: { _controller: NPResourcesBundle:Category:delete }
    requirements:
      id: \d+

np_resources_category_groupprocess:
    pattern: /groupprocess
    defaults: { _controller: NPResourcesBundle:Category:groupProcess }