<?php

namespace NP\Bundle\ModuloBundle\Entity;

use Cms\Bundle\AdminBundle\Entity\Traits\BaseAdminEntityRepository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends SortableRepository {
	use BaseAdminEntityRepository;
}
