_assetic:
    resource: .
    type:     assetic

cms_admin_dashboard:
    pattern:  /
    defaults: { _controller: NPAdminBundle:AdminDashboard:index }

fos_user:
    resource: "@CmsAdminBundle/Resources/config/routing/admin_user.yml"
    prefix: /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

np_modulo_gallery:
    resource: "@NPModuloBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery
np_modulo_gallery:
    resource: "@NPModuloBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery
np_modulo_picture:
    resource: "@NPModuloBundle/Resources/config/routing/picture.yml"
    prefix:   /picture
np_modulo_news:
    resource: "@NPModuloBundle/Resources/config/routing/news.yml"
    prefix:   /news
np_modulo_event:
    resource: "@NPModuloBundle/Resources/config/routing/event.yml"
    prefix:   /event
np_modulo_resources_category:
    resource: "@NPModuloBundle/Resources/config/routing/resources.yml"
    prefix:   /resources

