parameters:
    np_modulo.service.upload: NP\Bundle\ModuloBundle\Service\UploadService
    np_modulo.subscriber.upload: NP\Bundle\ModuloBundle\Entity\UploadSubscriber
#    np_modulo.subscriber.versionnable: NP\Bundle\ModuloBundle\Entity\VersionnableSubscriber

services:
    np_modulo.service.upload:
        class: %np_modulo.service.upload%
        arguments: [@service_container]

    np_modulo.subscriber.upload:
        class: %np_modulo.subscriber.upload%
        arguments: [@np_modulo.service.upload]
        tags: [{ name: doctrine.event_subscriber }]

#    np_modulo.subscriber.versionnable:
#        class: %np_modulo.subscriber.versionnable%
#        tags: [{ name: doctrine.event_subscriber }]
