<?php

namespace NP\Bundle\GalleryBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends SortableRepository {
    
    protected $config = array('groups'=>null);

    public function deleteOne($id)
    {
        $this->deleteGroup(array($id));
    }

    public function deleteGroup($ids)
    {
        $qb = $this->createQueryBuilder('g');

        $qb->delete('NPGalleryBundle:Gallery', 'g')
                ->where($qb->expr()->in('g.id', $ids))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }

    public function publishGroup($ids)
    {
        foreach($this->findBy(array('id'=>$ids)) as $entity) {
            $entity->setPublished(true);
            $this->_em->persist($entity);
        }
        
        $this->_em->flush();
    }

    public function unpublishGroup($ids)
    {
        foreach($this->findBy(array('id'=>$ids)) as $entity) {
            $entity->setPublished(false);
            $this->_em->persist($entity);
        }
        
        $this->_em->flush();
    }
    
    public function orderGroup($ids) {
        foreach($this->findBy(array('id'=>$ids)) as $i=>$entity) {
            $entity->setPosition($i);
            $this->_em->persist($entity);
        }
        
        $this->_em->flush();
    }
}
