np_event_event_index:
    pattern: /
    defaults: { _controller: NPEventBundle:Event:index }

np_event_event_show:
    pattern: /{id}/show
    defaults: { _controller: NPEventBundle:Event:show }
    requirements:
      id: \d+

np_event_event_new:
    pattern: /new
    defaults: { _controller: NPEventBundle:Event:new }

np_event_event_edit:
    pattern: /{id}/edit
    defaults: { _controller: NPEventBundle:Event:edit }
    requirements:
      id: \d+

np_event_event_delete:
    pattern: /{id}/delete
    defaults: { _controller: NPEventBundle:Event:delete }
    requirements:
      id: \d+

np_event_event_groupprocess:
    pattern: /groupprocess
    defaults: { _controller: NPEventBundle:Event:groupProcess }
