np_modulo_admin_news_index:
    pattern: /
    defaults: { _controller: NPModuloBundle:News:index }

np_modulo_admin_news_show:
    pattern: /{id}/show
    defaults: { _controller: NPModuloBundle:News:show }
    requirements:
      id: \d+

np_modulo_admin_news_new:
    pattern: /new
    defaults: { _controller: NPModuloBundle:News:new }

np_modulo_admin_news_edit:
    pattern: /{id}/edit
    defaults: { _controller: NPModuloBundle:News:edit }
    requirements:
      id: \d+

np_modulo_admin_news_delete:
    pattern: /{id}/delete
    defaults: { _controller: NPModuloBundle:News:delete }
    requirements:
      id: \d+

np_modulo_admin_news_publish_toggle:
    pattern: /{id}/publish_toggle
    defaults: { _controller: NPModuloBundle:News:publishToggle }
    requirements:
      id: \d+

np_modulo_admin_news_group_process:
    pattern: /group_process
    defaults: { _controller: NPModuloBundle:News:groupProcess }

np_modulo_admin_news_order:
    pattern: /order
    defaults: { _controller: NPModuloBundle:News:order }