np_modulo_admin_category_index:
    pattern: /
    defaults: { _controller: NPModuloBundle:Category:index }

np_modulo_admin_category_show:
    pattern: /{id}/show
    defaults: { _controller: NPModuloBundle:Category:show }
    requirements:
      id: \d+

np_modulo_admin_category_new:
    pattern: /new
    defaults: { _controller: NPModuloBundle:Category:new }

np_modulo_admin_category_edit:
    pattern: /{id}/edit
    defaults: { _controller: NPModuloBundle:Category:edit }
    requirements:
      id: \d+

np_modulo_admin_category_delete:
    pattern: /{id}/delete
    defaults: { _controller: NPModuloBundle:Category:delete }
    requirements:
      id: \d+

np_modulo_admin_category_group_process:
    pattern: /group_process
    defaults: { _controller: NPModuloBundle:Category:groupProcess }

np_modulo_admin_category_publish_toggle:
    pattern: /{id}/publish_toggle
    defaults: { _controller: NPModuloBundle:Category:publishToggle }
    requirements:
      id: \d+

np_modulo_admin_category_order:
    pattern: /order
    defaults: { _controller: NPModuloBundle:Category:order }